export const LOGIN_REQUEST = `LOGIN_REQUEST`;
export type LOGIN_REQUEST = typeof LOGIN_REQUEST;

export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS;

export const LOGIN_FAILED = `LOGIN_FAILED`;
export type LOGIN_FAILED = typeof LOGIN_FAILED;

export type AUTH_ACTION_TYPES = LOGIN_REQUEST | LOGIN_SUCCESS | LOGIN_FAILED;
