export const LEVEL_REQUEST = `LEVEL_REQUEST`;
export type LEVEL_REQUEST = typeof LEVEL_REQUEST;

export const LEVEL_RESPONSE = `LEVEL_RESPONSE`;
export type LEVEL_RESPONSE = typeof LEVEL_RESPONSE;

export type GAME_ACTION_TYPES = LEVEL_REQUEST | LEVEL_RESPONSE;
