export const LEVEL_REQUEST = `LEVEL_REQUEST`;
export type LEVEL_REQUEST = typeof LEVEL_REQUEST;

export const LEVEL_RESPONSE = `LEVEL_RESPONSE`;
export type LEVEL_RESPONSE = typeof LEVEL_RESPONSE;

export const FINISH_REQUEST = `FINISH_REQUEST`;
export type FINISH_REQUEST = typeof FINISH_REQUEST;

export const FINISH_RESPONSE = `FINISH_RESPONSE`;
export type FINISH_RESPONSE = typeof FINISH_RESPONSE;

export type GAME_ACTION_TYPES =
  | LEVEL_REQUEST
  | LEVEL_RESPONSE
  | FINISH_REQUEST
  | FINISH_RESPONSE;
